name: Update Profile SVGs

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta a la medianoche (UTC) todos los días
  workflow_dispatch:      # Permite ejecutarlo manualmente desde la web de GitHub

permissions:
  contents: write         # Necesario para que el bot pueda hacer push de las imágenes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecuta el script tomando los secretos desde GitHub y el resto localmente
      - name: Ejecutar script de estadísticas
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: mv-mnl
          NAME_HEADER: manuel@mv-mnl
          OS: Arch Linux (Hyprland)
          HOST: Custom Build
          KERNEL: Linux
          IDE: Neovim, VSCode
          LANG_PROG: Python, Bash, JS, C++
          LANG_COMP: HTML, CSS, JSON
          LANG_REAL: Spanish, English
          HOBBY_SW: Tiling WMs, Dotfiles, Scripting
          HOBBY_HW: PC Building
          HOBBY_OTH: Music, Gaming
          EMAIL_PERS: mmelende.com
          EMAIL_WORK: manuel.work@example.com
          INSTA: mv.mnl
          DISCORD: mv-mnl
        run: python today.py

      - name: Commit y Push de los cambios
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dark_mode.svg light_mode.svg cache/
          git commit -m "🤖 Auto-update de estadísticas de GitHub" || echo "Sin cambios para commitear"
          git push
